### PR TITLE
Setup pa11y accessibility check

### PR DESCRIPTION
**Pull request by senthil10**
Setting up a (scheduled) workflow to run `pa11ly` to automatically check for accessibility issues.

### CODE REVIEW

**Comment by senthil10** [comment]
The final accessibility fixes are deployed now, so this PR is now ready to be reviewed and merged.

**Comment by Ziip-dev** [comment]
Do I have a way to test this before approving?

**Comment by senthil10** [comment]
@Ziip-dev I have tested it in my own [test repo](https://github.com/senthil10/test_actions/actions/runs/10595574099) before making it ready for review. You can have look and if you wanna test it yourself, you can the workflow and config file to your own repo and try :)

**Comment by senthil10** [comment]
@Ziip-dev that is a warning from `actions/checkout@v3` step, I believe `checkout` uses `node 16.x`., we get that warning in all our currents action too :) 

But it is good spot anyway, since I see it all the time maybe I sub-consciously ignored it 😄 I will make a new PR to update the `checkout` version 👍

**Pull request merged**
