### PR TITLE
Use only official images

### PR DESCRIPTION
**Pull request by senthil10**
Using only official linux and webserver images

### CODE REVIEW

**Comment by eriksjolund** [comment]
The Dockerfile makes use of multi-stage syntax:
https://docs.docker.com/build/building/multi-stage/

For example
```
FROM alpine:latest AS build
```

but there is no COPY command, such as
```
COPY --from=build /bin/hello /bin/hello
```

What is the reason for using multi-stage syntax?
 It seems the dockerfile could also be splitted into two separate dockerfiles.

**Comment by senthil10** [comment]
@eriksjolund yes, it's a multi stage build. First is used to build the html files using hugo. Then in the second stage the generated html files are copied (please see line 19) 🙂

**Comment by eriksjolund** [comment]
@senthil10 Ah, of course, I need to click the GitHub web interface to expand and see the whole file. Now it makes sense.

**Review by sandstromviktor — APPROVED** [review]
I added some minor remarks if you want to optimize the image further. Maybe consider running `hadolint` on the Dockerfiles to spot these kind of things.

**Pull request merged**
